### ISSUE TITLE
Failure in creating an index

### ISSUE THREAD

**Issue by LucilaT** [kingsfordgroup/sailfish#112]
UPDATE: I have solved it. It was a problem with the assembly.fasta file.

Hi,
I am trying to create an index of my assembly and I obtained this error:

**FAILURE: return code from libdivsufsort() was -1**

The command I used is the following:
`salmon index -t assembly.fasta -i assembly_index --type quasi -k 31`

Any ideas of what can be happening? Any help is welcome.
Thank you in advance,
Lucila

**Comment by rob-p** [comment]
Hi @lucilaT,

  Thanks for reporting the issue and the fix.  I'd just like to point you at our [Salmon tool](www.github.com/COMBINE-lab/salmon), which is the successor to sailfish.  It is much more actively maintained and frequently updated, and has many new features not available in Sailfish.

Best,
Rob
