### ISSUE TITLE
Planned Feature: Transition Jellyfish dependency to 2.x

### ISSUE THREAD

**Issue by kingsfordgroup** [kingsfordgroup/sailfish#12]
Since Jellyfish 2 is now the official (and continually maintained) version of Jellyfish, Sailfish will transition its dependency from Jellyfish 1.x to 2.x.  This feature is in progress and, in addition to simplifying the code, seems to further improve quantification speed.

**Comment by rob-p** [comment]
This transition was made during the initial development of salmon, and jellyfish 2 is used in all new versions of sailfish and salmon.  Since this is complete, I'm closing this enhancement.
