### ISSUE TITLE
parsing gz files

### ISSUE THREAD

**Issue by jtmieg** [kingsfordgroup/sailfish#20]
Since we normally keep all fasta fastq files in .gz format
it is annoying to create a decompressed directory just for sailfish.
It would be nice if sailfish accepted .gz files
   -1 f.1.fastq.gz  -2 f.2.fastq.gz
you would just pipe the inputs internally using gunzip either
if the files are called *.gz or if the flag --gzi (--gzipped_input) is set

**Comment by rob-p** [comment]
I'm now considering the possibility of implementing this internally, though the availability  of this feature is dependent on some tentative updates to the underlying fasta/fastq parser we use (i.e. see [here](https://github.com/gmarcais/Jellyfish/issues/47)).  Once the Jellyfish parser supports directly reading from `istream`s, it should be very easy to support compressed files directly.
