### ISSUE TITLE
jellyfish hpp files and HeptamerIndex.cpp

### ISSUE THREAD

**Issue by sewen67** [kingsfordgroup/sailfish#23]
Hi all,
       I am trying to view the source code in XCode. However, I could not find any of the jellyfish.hpp files (for example jellyfish/sequence_parser.hpp) in the "sailfish-0.6.3" folder. Should I download it from the Internet? Morevoer, when I "build" the project in XCode, it returns a wrong message in the "HeptamerIndex.cpp" line 58 saying that "C++ requires a type specifier for all declarations". Any suggestions?

Thank you.

sewen67

**Comment by rob-p** [comment]
Sorry @sewen67, that it seems like this ticket has been open forever!  The build system pulls in jellyfish as a dependency when it is invoked.  This prevents us from having to keep the source code for all of our dependencies directly in our repository.  HeptamerIndex is not actually used in any live code, so I'm guessing the problem there is XCode trying to make a build file when it doesn't really know what's live or not.  In any case, all of the development for the past 8 months or so has been on the [develop branch](https://github.com/kingsfordgroup/sailfish/tree/develop) of the repo, where the big development has been salmon; the successor to sailfish.
