### ISSUE TITLE
sailfish quant crashes

### ISSUE THREAD

**Issue by ttriche** [kingsfordgroup/sailfish#25]
[ttriche@hpc3398:staging]$ sailfish index -t hg19_transcriptome/hg19_transcripts.fa -o hg19_transcriptome -k 20
Version Info: Could not resolve upgrade information in the alotted time.
Check for upgrades manually at www.cs.cmu.edu/~ckingsf/sailfish.
writing logs to hg19_transcriptome/logs
readFile: hg19_transcriptome/hg19_transcripts.fa, 
file hg19_transcriptome/hg19_transcripts.fa: 
reading from 1 streams
reading from hg19_transcriptome/hg19_transcripts.fa
hit eof!d 247000 transcripts (4333) transcripts/s

Checking that jellyfish hash is up to date
All index files seem up-to-date.
To force Sailfish to rebuild the index, use the --force option.

Exiting, log location: hg19_transcriptome/logs/sailfish.g2log.20140515-155220.log
[ttriche@hpc3398:staging]$ 
[ttriche@hpc3398:staging]$ 
[ttriche@hpc3398:staging]$ sailfish quant -i ../hg19_transcriptome -l "T=PE:O=><:S=U" \
> -1 tAML03/tAML03_read1.fastq -2 tAML03/tAML03_read2.fastq -o tAML03 
Version Info: Could not resolve upgrade information in the alotted time.
Check for upgrades manually at www.cs.cmu.edu/~ckingsf/sailfish.
Library format { type:paired end, relative orientation:toward, strandedness:unstranded }
reading index . . . Sailfish terminated with return code 11
sailfish: /home/robp/Sailfish-0.6.3-Source/src/QuantificationDriver.cpp:152: int runKmerCounter(const string&, uint32_t, const string&, const std::vector<ReadLibrary>&, const string&, bool): Assertion `status == 0' failed.
Aborted

**Comment by rob-p** [comment]
Since v0.7.0, there have been **very substantial** improvements to the algorithm.  Sailfish now uses a considerably simpler (yet faster and more versatile) index.  I believe that this issue should be resolved, and strongly encourage you to try out the newest version of Sailfish if you haven't used it in a while.
