### ISSUE TITLE
cleanup of orientation string

### ISSUE THREAD

**Issue by dakl** [kingsfordgroup/sailfish#27]
Hi, 

I've used sailfish in a pipeline recently, and adding it turned out more complex than other command line tools. The reason for this is the --libtype parameter, which needs to be escaped on several levels, depending on the pipeline you use, and how commands are passed internally. 

The current format is somewhat clunky, and I suggest cleaning it up by splitting it to several parameters, and avoding characters that need to be escaped. 

    -l "T=PE:O=><:S=SA"

could be split into

    --paired --orientation fr --strands sa

where `--paired` sets paired mode (default could be single), `--orientation fr` sets forward-reverse relative orientation (currently `><`). This would then mean that the libtype

    -l "T=SE:S=U"

would collapse to nothingness (defaults to single-end, non-stranded). Clean! :)

**Comment by rob-p** [comment]
Hi @dakl,

  The original library format strings (though they have a nice visual flair), were clearly un-necessarily complex.  Further, the requirement of wrapping them in quotations sometimes made ensuring proper escaping of the library format string difficult.  In the recent releases, we have moved to a new library format description that is detailed [here](http://sailfish.readthedocs.org/en/master/library_type.html).  Unfortunately, it doesn't have the benefit of single-end, non-stranded, reads collapsing to nothing, but it does collapse to `-l U` — which is considerably better than before!

--Rob
