### ISSUE TITLE
quant strand specific RNA seq recognized as "unstranded"

### ISSUE THREAD

**Issue by bioinforME** [kingsfordgroup/sailfish#28]
Hi,
I am new to sailfish. I have some paired-end strand-specific RNA seq data generated using dUTP/TruSeq protocol i want to quantify.

The library type parameter i used with quant command is :

-l "T=PE:O=><:S＝AS"

But i found it was recognized as "unstranded":

"Version Info: Could not resolve upgrade information in the alotted time.
Check for upgrades manually at www.cs.cmu.edu/~ckingsf/sailfish.
Library format { type:paired end, relative orientation:toward, strandedness:unstranded }
reading index . . . done
...."

I was wondering whether i have used the correct parameters there, or whether i should be worried.

Thank you.

Cheers.

**Comment by rob-p** [comment]
Should be fixed in the newest releases.
