### ISSUE TITLE
Indexing never ends

### ISSUE THREAD

**Issue by delafont** [kingsfordgroup/sailfish#29]
"sailfish index" always freezes a few seconds before ending the "Parsing transcripts and building k-mer equivalence classes" step - see the log below. I tried it several times and it ran over night on a cluster, too. Both are Unix machines and my sailfish version is 0.6.3.

> sailfish index --force --transcripts mm10_trx_d8a0991e3e6b5e1611276a19cd2efe4d23b59253.fa --tgmap ../mm10_d8a0991e3e6b5e1611276a19cd2efe4d23b59253_renamed.gtf --kmerSize 20 --out index

Version Info: This is the most recent version

writing logs to index2/logs
readFile: mm10_trx_d8a0991e3e6b5e1611276a19cd2efe4d23b59253.fa,
file mm10_trx_d8a0991e3e6b5e1611276a19cd2efe4d23b59253.fa:
reading from 1 streams
reading from mm10_trx_d8a0991e3e6b5e1611276a19cd2efe4d23b59253.fa
hit eof!d 83000 transcripts (2677) transcripts/s

Running Jellyfish on transcripts
file: mm10_trx_d8a0991e3e6b5e1611276a19cd2efe4d23b59253.fa has size 172113710 bytes
running jellyfish with --timing=index2/jf.time -m 20 -t 24 -o index2/jf.counts -s 206536452 mm10_trx_d8a0991e3e6b5e1611276a19cd2efe4d23b59253.fa
In Jellyfish process. Counting transcript kmers
Jellyfish terminated with return code 0
Jellyfish finished
transcriptHash size is 79160767
Building a perfect hash from the Jellyfish hash.
 122.497177s wall, 119.710000s user + 2.760000s system = 122.470000s CPU (100.0%)
saving keys in perfect hash . . . 2.319118s wall, 52.820000s user + 0.020000s system = 52.840000s CPU (2278.5%)
done
took: 0.0292969 us / key
writing index to file "index2/transcriptome.sfi"
writing transcript counts to file "index2/transcriptome.sfc"
done writing index
done writing transcript counts
building transcript to gene map using gtf file [../mm10_d8a0991e3e6b5e1611276a19cd2efe4d23b59253_renamed.gtf] . . .
done
Saving transcritpt to gene map to ["index2/transcriptome.tgm"]
Reading transcript index from ["index2/transcriptome.sfi"] . . .done
Reading transcript counts from [index2/transcriptome.sfc] . . .read length = 0, numLengths = 0
done
reading from 1 streams
reading from mm10_trx_d8a0991e3e6b5e1611276a19cd2efe4d23b59253.fa
Number of kmers : 79160767
Parsing transcripts and building k-mer equivalence classes
hit eof!===========================>                       ] ETA 23s
 90% [==============================================>      ] ETA 5s

(stays like that > 24h)

**Comment by rob-p** [comment]
All such issues should be resolved with the newer versions of Sailfish. The indexing and mapping strategy have been substantially modified and indexing is now a much quicker operation.  Please let us know if this problem persists.
