### ISSUE TITLE
Expression estimation of similar transcript variants of the same gene

### ISSUE THREAD

**Issue by Biotechnologe** [kingsfordgroup/sailfish#36]
Hello,

first of all I want to say that I really like the speed of Sailfish for expression quantification. I am working in the field of single-cell transcriptomics and have to deal with hundreds of single-cell RNA-seq libraries for the data analysis, thus computation time is a critical factor.

I used the latest version of Sailfish to quantify several hundred paired-end RNA-seq libraries using the RefSeq transcriptome model (ftp://ftp.ncbi.nlm.nih.gov/refseq/H_sapiens/mRNA_Prot/human.rna.fna.gz) for index construction. As a follow up step I created a table that combines the RPKM columns of all single-cell quant.sf files, with transcript IDs as row names and cell IDs as column names.

In my initial analysis I noticed that many of the RefSeq annotations are transcript variants of the same gene. I wanted to find out how Sailfish deals with the expression of similar transcript variants of the same gene. A quick look at a few genes showed that different transcript variants have different RPKM values which seem to indicate differential splicing in individual single cells. However, since transcript variants often share many common exons of the same gene, I wonder how the expression estimation for some variants is 0, while in another very similar variant it is high. I would expect that kmer counts for transcripts with very similar sequences would be high for all similar variants.

For testing I picked the FOS gene (NM_005252.3), which only has one annotated transcript. I created a reference file for the index creation that only contains 2 transcripts. The original FOS sequence labeled >FOS.1 and an exact copy of the original FOS sequence labeled >FOS.2. In another test case I created a file with the original FOS sequence >FOS.1 followed by >FOS.3, which contains the FOS sequence with the last 120 bases deleted from the tail. I created the index for each of these test files and performed the quantification on a few selected single-cells afterwards, by piping the fastq files into sailfish quant executed within the parallel command (for conveniently saving the output of each pair of single-cell fastq files in appropriately named output folders). No errors where reported while running the sailfish commands and all required output files have been created.

```{r indexing, eval=FALSE, engine='sh'}
sailfish index -t FOS_duplicated.fa -o index_duplicated -f -k 20
sailfish index -t FOS_duplicated_edited.fa -o index_duplicated_edited -f -k 20

# case 1
parallel -j1 'sailfish quant \
                         -i index_duplicated \
                         -l "T=PE:O=><:S=U" \
                         -1 <({}_R1_001.fastq.gz) \
                         -2 <({}_R2_001.fastq.gz) \
                         -o duplicatedFOS/{}/'

# case 2
parallel -j1 'sailfish quant \
                         -i index_duplicated_edited \
                         -l "T=PE:O=><:S=U" \
                         -1 <({}_R1_001.fastq.gz) \
                         -2 <({}_R2_001.fastq.gz) \
                         -o duplicatedFOS_edited/{}/'
```

In case 1 I got identical RPKM values for FOS.1 and FOS.2, but also for all individal cells, which can't be true, because looking at the expression profile in a genome browser clearly showed different expression patterns for the FOS gene in different cells. For case 2 I got much higher RPKM values for the shorter FOS.3 transcript, compared to the original FOS.1 transcript. Furthermore, in some cells FOS.1 was 0 while FOS.3 had a very high RPKM value. Also, the RPKM values seem to be way too high (between 19000 and 52000). In my orginal quantification with the unmodified RefSeq transcriptome and all single cells none of the values exceeded 800.

How can it be that transcripts with close sequence similarity report 0 expression in the original full sequence version of one transcript and high expression in the edited version? I already aggregated (sum) all transcripts that share identical gene symbols, but I am not sure whether the observed differences among gene specific transcript variants are actually meaningful or just a result of the sailfish quantification estimation method being unable to give correct estimates for transcript variants in case of large sequence similarities.

If necessary I can share the fastq files that we used for sailfish quantification and the bam files that were used for visualization in a genome browser.

**Comment by rob-p** [comment]
Version 0.7.0 and above should mitigate this problem substantially as we've adopted both a faster and more accurate methodology.  Please let us know if you continue to observe such behavior.
