### ISSUE TITLE
[salmon] improve clarity of help messages

### ISSUE THREAD

**Issue by Blahah** [kingsfordgroup/sailfish#41]
When a user fails to provide all the required arguments to `salmon quant`, they are met with a message like this:

```bash
$ ./salmon quant
Version Info: This is the most recent version

# salmon (smem-based) v0.1.0
# [ program ] => salmon
# [ command ] => quant
Exception : [boost::bad_any_cast: failed conversion using boost::any_cast]
./salmon quant was invoked improperly.
For usage information, try ./salmon quant --help
Exiting.
```

Running `salmon quant --help` as suggested (or `salmon quant --help-alignment`, etc.) doesn't provide either:

1. an example minimal command
2. an indication of which arguments are required

It would be useful to provide both.

**Comment by rob-p** [comment]
Most of this should be OK.  Feel free to reopen if you find something else.
