### ISSUE TITLE
ERROR: sailfish count invoked improperly?

### ISSUE THREAD

**Issue by mdapas1** [kingsfordgroup/sailfish#45]
I'm attempting to quantify human paired-end reads from TCGA, using Ensembl GRCh37 transcriptome annotation, with the Linux installation of Sailfish 0.6.3. I was able to generate the index successfully (or so it appears), but I am unable to run Sailfish Quant to completion.

I am running the following command:
> sailfish quant -p 40 -f -i $LIB/index -l "T=PE:O=><:S=U" -1 $READS_DIR/G17190.TCGA-06-0174\
-01A-01R-1849-01.2.bam_1.fastq -2 $READS_DIR/G17190.TCGA-06-0174-01A-01R-1849-01.\
2.bam_2.fastq -o $LIB/output

After the reads are processed, I receive the following error:
> ERROR: sailfish count (subordinate command) invoked improperly.
Sailfish terminated with return code 256
sailfish: /home/robp/Sailfish-0.6.3-Source/src/QuantificationDriver.cpp:152: int runKmerCounter(const string&, uint32_t, const string&, const std::vector<ReadLibrary>&, const string&, bool): Assertion `status == 0' failed.

I've tried a number of different library type strings, just in case, but this error persists. It isn't clear what this error means. 

I've used this data before with a number of other quantification tools, so I don't think it's an issue with the source data. Any help would be greatly appreciated, thanks.

- Matt

**Comment by vd4mmind** [comment]
@mdapas1  did you find a workaround for this issue? I have just started working with Sailfish 2 days back and I encountered the same problem. My library type is also the same as ```"T=PE:O=><:S=U"``` . I would appreciate if you can give me some feedback. I am using the latest version of the sailfish

**Comment by rob-p** [comment]
I'm not sure what's causing this.  However, the way that quantification works has been substantially improved and simplified as of version 0.7.0 and this error should no longer be a problem.  Please feel free to re-open this or open another issue should you continue to encounter this problem with the new version.
