### ISSUE TITLE
Time to compute hash function

### ISSUE THREAD

**Issue by aconz2** [kingsfordgroup/sailfish#46]
I've been trying to build the index for a large set of genes, ~4M, and Sailfish is stalled on computing the MPHF for 3 days. I am using kmer size 17 and have previously counted the dataset with Jellyfish and know that there are ~2B distinct kmers. From the BDZ docs, it seems like it takes ~34 bytes/key which gives ~80GB of RAM which is not a problem on the machine I'm using. I'm wondering if this is a bug or if typical usage is with a smaller number of distinct kmers.

Note: I have also tried running a subset of the genes, 1M, and also time out at 3 days (due to cluster access time). And I have run a tiny set to verify it is a working install. I can continue running smaller subsets but was wondering if this was a typical size. 

Thanks
Andrew

**Comment by rob-p** [comment]
Hi @aconz2,

  While we are looking into more efficient minimal perfect hash construction implementations (e.g. [emph](https://github.com/ot/emphf)), the best way to deal with very large transcriptomes is just to use salmon.  At this point, it has had extensive testing, and should be as-fast-or-faster (and even more accurate) than sailfish.  I'm going to close this ticket for now, but please let us know if that solution works for you or if you have any other feedback.

Thanks!
Rob

**Comment by aconz2** [comment]
Awesome, interesting to hear about emph (thanks for the link). And will be testing out Salmon.
