### ISSUE TITLE
Encore for salmon install issue!

### ISSUE THREAD

**Issue by cganote** [kingsfordgroup/sailfish#53]
Hi Rob,

Sorry for bringing up one more complaint - I installed sailfish correctly, then realized that I was on the master branch, and didn't install Salmon proper.
I'm almost there!:
Linking CXX executable salmon
cd /N/soft/rhel6/salmon/sailfish/build/src && /N/home/c/g/cganote/Mason/bin/cmake-2.8.10.2/bin/cmake -E cmake_link_script CMakeFiles/salmon.dir/link.txt --verbose=1
/N/soft/rhel6/gcc/4.7.2/bin/g++   -DHAVE_LOGGER -g -funroll-loops -fPIC -fomit-frame-pointer -Ofast -DHAVE_ANSI_TERM -DHAVE_SSTREAM -Wall -std=c++11 -Wreturn-type -Werror=return-type -Wno-deprecated-register -Wno-unused-local-typedefs    CMakeFiles/salmon.dir/QSufSort.c.o CMakeFiles/salmon.dir/is.c.o CMakeFiles/salmon.dir/bwt_gen.c.o CMakeFiles/salmon.dir/bwtindex.c.o CMakeFiles/salmon.dir/Salmon.cpp.o CMakeFiles/salmon.dir/BuildSalmonIndex.cpp.o CMakeFiles/salmon.dir/SalmonQuantify.cpp.o CMakeFiles/salmon.dir/FragmentLengthDistribution.cpp.o CMakeFiles/salmon.dir/SalmonUtils.cpp.o CMakeFiles/salmon.dir/StadenUtils.cpp.o CMakeFiles/salmon.dir/FASTAParser.cpp.o CMakeFiles/salmon.dir/ErrorModel.cpp.o CMakeFiles/salmon.dir/SalmonQuantifyAlignments.cpp.o  -o salmon  -L/N/soft/rhel6/salmon/sailfish/lib  -L/N/soft/rhel6/salmon/sailfish/external/install/lib  -L/N/soft/rhel6/boost/1.55.0/stage/lib  -L/usr/lib/gcc/x86_64-redhat-linux/4.4.7 -rdynamic libsailfish_core.a -lgff /N/soft/rhel6/boost/1.55.0/stage/lib/libboost_iostreams.a /N/soft/rhel6/boost/1.55.0/stage/lib/libboost_filesystem.a /N/soft/rhel6/boost/1.55.0/stage/lib/libboost_system.a /N/soft/rhel6/boost/1.55.0/stage/lib/libboost_thread.a /N/soft/rhel6/boost/1.55.0/stage/lib/libboost_timer.a /N/soft/rhel6/boost/1.55.0/stage/lib/libboost_chrono.a /N/soft/rhel6/boost/1.55.0/stage/lib/libboost_program_options.a /N/soft/rhel6/boost/1.55.0/stage/lib/libboost_serialization.a ../../external/install/lib/libstaden-read.a -Wl,-Bstatic -lz -Wl,-Bdynamic ../../external/install/lib/libcmph.a ../../external/install/lib/libjellyfish-2.0.a ../../external/install/lib/libbwa.a -lm -llzma -lbz2 ../../external/install/lib/liblib_g2logger.a -ltbb -ltbbmalloc -lshark -lgomp -lrt -lpthread -Wl,-rpath,"\$ORIGIN/../lib:\$ORIGIN/../../lib:\$ORIGIN/" 
/usr/bin/ld: cannot find -llzma
collect2: error: ld returned 1 exit status
make[2]: *** [src/salmon] Error 1
make[2]: Leaving directory `/N/soft/rhel6/salmon/sailfish/build'
make[1]: *** [src/CMakeFiles/salmon.dir/all] Error 2
make[1]: Leaving directory `/N/soft/rhel6/salmon/sailfish/build'
make: *** [all] Error 2
I installed and compile liblzma from here:
http://tukaani.org/xz/
After adding the library to my ld_lib_path I'm still getting that error at the last step.

Thanks so much for your patience!
-Carrie

**Comment by rob-p** [comment]
Did you ever get this resolved?  If not, you can reopen this issue in the salmon repository.
