### ISSUE TITLE
Doker image for salmon?

### ISSUE THREAD

**Issue by rob-p** [kingsfordgroup/sailfish#56]
Hi all,

  Though we make a concerted effort to ease the process as much as possible, by providing an "automated" build system and multiple different pre-built binaries, library version hell seems to plague at least some fraction of our users.  The problem is that Linux executables, it seems, are very particular about the versions of system libraries available where they are run.  We've done our best to mitigate these issues by moving to a largely statically linked binary (the only library dependency which remains dynamically linked is Intel TBB, which does not / can not build a static library).

  However, the crux of the issue is that regardless of how well the libraries on which we depend are statically linked, certain libraries (e.g. libstdc++ and libc) cannot be reliably linked statically.  Thus, incompatible versions of libstdc++ and libc need to be packaged along with the binary.  This solves problems on some, but not all systems.

  I'd like to get a feel for how helpful it would be (if at all) if we were to provide some [Docker](https://www.docker.com/) images for salmon.  Since the image would run in its own Docker container, we could all but eliminate library dependency hell.  On the other hand, to make use of the images, one would have to have an OS recent enough to support Docker and would have to have the Docker system, itself, installed (which, I understand, requires administrative privileges).  Thus, before investing time in trying to make Docker images available, I wanted to see how many people think this might ease their installation of salmon.

**Comment by rob-p** [comment]
@ctb has already taken care of this for Salmon, we should be able to adopt [this](https://github.com/ctb/2015-docker-building/tree/master/salmon) for sailfish as well.

**Comment by ctb** [comment]
Yep - do what you will with it, obviously!
