### ISSUE TITLE
sailfish quant error

### ISSUE THREAD

**Issue by MKreitzman** [kingsfordgroup/sailfish#6]
Hi, 
I'm trying to test out SailFish for  the first time. I downloaded the linux binary version 6.0. The installation test worked, as did the indexing step on my transcriptome reference. But, I'm running into a problem in the quant step.

I'm running it in the following way:
```sailfish quant -i /SailFish/Z00382/sample_index -r /test_data/strand_specific/fastqs/Z00382-control/D137PACXX_5_1.fastq /test_data/strand_specific/fastqs/Z00382-control/D137PACXX_5_3.fastq -o /SailFish/Z00382/sample_quant 2> /SailFish/Z00382/sample_quant/quant.log```

the output looks like this:
<pre>Version Info: A newer version of Sailfish is available.
If you are using the named-pipe input feature, please upgrade to the latest version.

In Sailfish Counting thread. Counting read kmers
reading index . . . done
index contained 101484059 kmers
Parsing sense reads
Parsing antisense reads
Parsing undirected reads
file /projects/mkreitzman_prj/expression_quantification_testing/testing/test_data/strand_specific/fastqs/Z00382-control/D137PACXX_5_1.fastq: 
ERROR
ERROR
ERROR
ERROR
ERROR
ERROR
ERROR
ERROR
ERROR
ERROR
ERROR
..and so on</pre>

I also tried to give the two fastq's using --forward and --reverse options, but got some sort of command line parsing error: 

<pre>Version Info: A newer version of Sailfish is available.
If you are using the named-pipe input feature, please upgrade to the latest version.

In Sailfish Counting thread. Counting read kmers
Program Options Error : [unrecognised option '--reverse/projects/mkreitzman_prj/expression_quantification_testing/testing/test_data/strand_specific/fastqs/Z00382-control/D137PACXX_5_3.fastq']. Exiting.
Sailfish terminated with return code 256
sailfish: /home/robp/SoftwareStaging/Sailfish-0.6.0-Source/src/QuantificationDriver.cpp:119: int runKmerCounter(const string&, uint32_t, const string&, const std::vector<std::basic_string<char> >&, const std::vector<std::basic_string<char> >&, const std::vector<std::basic_string<char> >&, const string&, bool): Assertion `status == 0' failed.
Aborted</pre>

Any advice would be much appreciated!

**Comment by rob-p** [comment]
These issues should all be resolved in the newest releases.  Please re-open this issue if you're still having such problems.
