### ISSUE TITLE
Salmon 0.2.3 release binary GLIBC issue

### ISSUE THREAD

**Issue by billytcl** [kingsfordgroup/sailfish#61]
Hi there, is it possible on your end to recompile the Salmon 0.2.3 binary with an older version of GLIBC?

I am getting an error that my GLIBC (2.15) is too old for what is required (2.17), and many users don't exactly have admin privileges or are too scared to put a new version onto their system.

I tried to compile it on my own but apparently my version of GCC is also too old.

**Comment by rob-p** [comment]
Hi @billytcl,

  Can you try the [latest Travis CI binary](https://github.com/kingsfordgroup/sailfish/releases/tag/TravisCI) of Salmon?  Version 0.2.3 is built on ubuntu 14.04, but the latest Travis CI build is built on ubuntu 12.04, so it may use an older version of glibc.  The Travis CI build is always the latest (successfully compiling) build, so it's actually a bit newer than v0.2.3.  If that version still gives you problems, I can explore explicitly building with an older glibc version.

--Rob

**Comment by billytcl** [comment]
I just downloaded the binary and can run salmon --help. Before it would crash immediately so I'm guessing it's working. Thanks!

**Comment by rob-p** [comment]
Excellent --- I'll assume that this means that executable is working, so I'm closing this issue.  If you encounter further (related) problems, please re-open it.
