### ISSUE TITLE
make formatting of salmon cmdline arguments consistent

### ISSUE THREAD

**Issue by Blahah** [kingsfordgroup/sailfish#65]
Minor style point: some of the salmon arguments are CamelCase and some are snake_case. Consistently using one would make me feel less ridiculous about noticing minor style inconsistencies in command-line tools.

**Comment by rob-p** [comment]
Thanks for the report; this should be resolved in v0.2.4.  Let us know if you discover any other hidden_discrepancies in CamelCasing.
