### ISSUE TITLE
wrong path for bwa compilation

### ISSUE THREAD

**Issue by noncodo** [kingsfordgroup/sailfish#68]
While trying to install salmon, the compiler searches for ./external/bwa-master however the files get extracted to ./external/bwa-master/bwa-master/

**Comment by rob-p** [comment]
Hi @noncodo,

  Thanks for reporting this, but I'm not able to reproduce it using the latest commit on any of my machines (the continuous integration server --- Ubuntu 12.04, Ubuntu 14.04, Ubuntu 14.10, or OSX 10.10).  Could you give us more details on your system and the output of the build system?

Thanks,
Rob

**Comment by noncodo** [comment]
I simply moved the bwa-master folder one dir up to get it going. However, I ran into quite a few additional compilation problems actually. The last one that really did my head in was relating to the lack of a C11 compiler, but then I discovered that the pre-compiled binary for CentOS 6.5 worked on our server (2.6.32-504.el6.x86_64 GNU/Linux CentOS 6.6  with GCC 4.8.4) and had a glass of scotch.

**Comment by rob-p** [comment]
Ahh --- Yes, the lack of a C++11 compiler is a non-starter.  I'm hoping that, since C++-14 is now the current *official* standard, this issue continues to be mitigated.  Until that time, we'll do our best to provide pre-compiled binaries for the platforms we can.

**Comment by aconz2** [comment]
If it amounts to anything, I can confirm the issue @noncodo was having with `bwa-master` being inside `external/bwa-master`. I was building salmon-v0.1.3

**Comment by rob-p** [comment]
Thanks for reporting this.  So the latest tagged version is v0.2.7.  I have an eta on v0.3.0 (currently HEAD of the develop branch) of tomorrow or this weekend.  In general, I was not previous creating a release for each tagged version (as development was proceeding very rapidly).  Now, however, I am doing this.  There was an issue earlier on when I switch the location from which bwa-master was being downloaded.  I suspect there was a commit (or small interval of commits) where this nested folder issue existed before I realized it.

**Comment by rob-p** [comment]
As an update to this, my current guess is that it may have something to do with too old a version of cmake (though that doesn't explain why *only bwa* is affected). Can you specify what version you are using?

**Comment by aconz2** [comment]
Not sure who this is directed at, but I was using v3.0.2. I have since deleted that build folder though so I'm likely not of much help.
