### ISSUE TITLE
Library bulk download - Port 80 is Blocked

### ISSUE THREAD

**Issue by carlitre** [kingsfordgroup/sailfish#70]
Hello Sailfish team, 

I am installing Salmon, and in the "make" step the attempts to access port 80 are unsuccessful since that port is blocked in my University's computing center. I'd like to know if there is a repository to bulk download all the libraries  (I tried http://www.cs.stonybrook.edu/~rp/files from Firefox but the site is not available). If I can bulk download them all, should I store them at /sailfish-0.2.2/external/ and then run make? Thank you.

Carlos

**Comment by rob-p** [comment]
Hi @carlitre,

  There are new locations for downloading the dependencies that, hopefully, are not blocked for you (e.g. most dependencies are pulled directly from GitHub).  Please let us know if you're still having this problem with the newest version of the software.

--Rob
