### ISSUE TITLE
New Sailfish release to fix linking error

### ISSUE THREAD

**Issue by LeeMendelowitz** [kingsfordgroup/sailfish#71]
There is this linking error in the sailfish 0.6.3 release that has since been resolved. I was trying to build sailfish from source and ran into the same error detailed [here](https://groups.google.com/forum/#!topic/sailfish-users/OEJDsyEEGIQ) in the users group:

```
/usr/bin/ld: cannot find -llib_activeobject
collect2: error: ld returned 1 exit status
```

Instead, I downloaded the latest source from the master branch (commit 6f6d2725f362973d21609dee30d4be74165268cf) and tried the build and it worked fine.

It would be useful to get this out as release 0.6.4 so people don't run into this problem trying to build from source on 0.6.3

**Comment by rob-p** [comment]
Hi Lee,

  Things have been *significantly* re-worked in the v0.7.0 branch.  Hopefully, this issue (and numerous others) should be resolved.
