### ISSUE TITLE
salmon index crashes with cryptic error

### ISSUE THREAD

**Issue by jdidion** [kingsfordgroup/sailfish#75]
Version: 0.3.0, built from source
Command: salmon index -t <(zcat transcripts.fa.gz) -i transcripts.index -p 48
Result:

Version Info: Could not resolve upgrade information in the alotted time.
Check for upgrades manually at www.cs.cmu.edu/~ckingsf/sailfish.
index ["transcripts.index"] did not previously exist  . . . creating it
[2015-03-26 18:06:01.797] [jointLog] [info] computeBiasFeatures( {[/dev/fd/63] , transcripts.index/bias_feats.txt, 1, 48)

readFile: /dev/fd/63,
file /dev/fd/63:
processed 265800 transcripts (88600) transcripts/ss
[bwa_index] Pack FASTA... [bns_fasta2bntseq] Failed to allocate 0 bytes at bntseq.c line 303: Success

Contents of index directory:
drwxr-sr-x 15 didionjp msfusion     4239 Mar 26 18:06 ..
-rw-r--r--  1 didionjp msfusion      140 Mar 26 18:02 indexing.log
drwxr-sr-x  2 didionjp msfusion       90 Mar 26 18:02 .
-rw-r--r--  1 didionjp msfusion        0 Mar 26 18:02 bwaidx.pac
-rw-r--r--  1 didionjp msfusion 23571322 Mar 26 18:02 bias_feats.txt

Contents of indexing.log:
[2015-03-26 18:02:43.960] [jointLog] [info] computeBiasFeatures( {[/dev/fd/63] , transcripts.index/bias_feats.txt, 1, 48)

**Comment by jdidion** [comment]
This appears to be a problem with using a process substitution to read from a gzipped file. When I unzip the file and build the index, it works fine. I'm guessing this is a unix issue rather than a salmon issue, so feel free to close. I would recommend putting a note in the docs regarding the possibility that this might happen and recommending to try again with the unizpped file if using a process substitution fails.

**Comment by rob-p** [comment]
Hi John,

  First, thanks for reporting this (*and* for reporting *back* that the issue seems to go away when you don't read the file using process substitution).  What's so strange about that error is that it occurs in the call out to the external library we're using for BWT construction (the venerable BWA codebase).  I have some speculation on what may be happening, and I'll leave the issue open until I see if I can verify it.

**Comment by antonkulaga** [comment]
I see it is closed, how did you solve it? I have this cryptic error all over again :(
