### ISSUE TITLE
Approaches to handling Ns in the reference

### ISSUE THREAD

**Issue by kingsfordgroup** [kingsfordgroup/sailfish#8]
I'm adding this issue as an "enhancement" thread, where users can provide suggestions about the best way to handle ambiguous bases in the reference sequence.  Currently, k-mers containing 'N's are discarded, and the associated transcript's effective length is adjusted accordingly.  However, there are other suggestions about potential ways to address such ambiguities.  [tjh48](https://github.com/tjh48) provided the following suggestions:

> I suppose for single Ns - and the current segfault occurs with a single N in the reference  - you could generate four different k-mer possibilities for the reference (one each where the N is replaced by A, C, T, G), and allow the sequence to match to any of these. If a  k-mer contains too many Ns, the number of possibilities probably increases by too  much to make this viable, but if there are too many Ns in a given k-mer there's no point in mapping to it, and it can reasonably be discarded.

> User option, defaulting to 2 Ns allowed in any given (reference) k-mer, with warnings above 4 and reports on how many k-mers (from how many transcripts) are discarded for too many Ns?
  
This is a reasonable solution, but how to handle k-mers that simultaneously map perfectly so some locations and imperfectly to others is not _a priori_ clear.  Solutions to this problem, alternative suggestions, and support for the simple but direct existing approach are welcome.

--Rob

**Comment by rob-p** [comment]
This is now handled by replacing the `N` sequences in the reference with pseudo-random nucleotides.   I'm closing this issue for the time being, but please feel free to comment here if there are better proposed solutions.
