### ISSUE TITLE
index broken

### ISSUE THREAD

**Issue by butterflyology** [kingsfordgroup/sailfish#82]
Just installed Sailfish 0.7.5 from the previous version (which worked fine). 

Installed the new version, rebuilt the index for my experiment, and now I get:

"[2015-10-05 14:39:23.044] [jointLog] [info] parsing read library format
there is 1 lib
Exception : [Error: The index version file Sail-0.3-index/versionInfo.json doesn't seem to exist.  Please try re-building the salmon index.]
/home/chamm/Sailfish/bin/sailfish quant was invoked improperly.
For usage information, try /home/chamm/Sailfish/bin/sailfish quant --help
Exiting."

I try rebuilding the index, including using --force and just deleting the directory with the index, and I still get this error. When I build the new index, it seems to have far less output then before. I hope this helps. 

Chris

**Comment by rob-p** [comment]
Hi Chris,

  When you say "previous" version, do you mean v0.6.3?  One thing that has changed (and I will update the documentation to make this more clean) is that the `k` value you provide to the indexer must be an *odd* value.  That means, you can't say e.g. `-k 18

**Comment by butterflyology** [comment]
Hi Rob, 

Thanks for your answer. Changing the K value returned the index functionality. Thanks. 

Chris

**Comment by rob-p** [comment]
No problem :).
