### ISSUE TITLE
Sailfish returns with error code 11

### ISSUE THREAD

**Issue by AbhijitBadve** [kingsfordgroup/sailfish#9]
Posting the error log below:
1.Info: I am running sailfish module on a cluster node of my organization. (serial job with Extreme Scalability Mode (ESM))
2. my command:
sailfish quant -i cDNA/Musmusculus/ -o  Musmusculus/Quant/SRR943356 -r Musmusculus/SRR943356.fastq -p 30
3. Log:
Sailfish for RNA-seq expression estimates , version 0.6.2 loaded.
Version Info: ### A newer version of Sailfish is available. ####
###
The newest version, available at https://github.com/kingsfordgroup/sailfish/releases
contains important bug fixes and some new features; please upgrade at your 
earliest convenience.
###
Undirected reads:[Musmusculus/SRR943343.fastq ]
Sense reads:[]
Anti-sense reads:[]
In Sailfish Counting thread. Counting read kmers
reading index . . . Sailfish terminated with return code 11
sailfish: /home/robp/SoftwareStaging/Sailfish-0.6.2-Source/src/QuantificationDriver.cpp:130: int runKmerCounter(const string&, uint32_t, const string&, const std::vector<std::basic_string<char> >

**Comment by rob-p** [comment]
The parser has been improved in the newer releases and hopefully you shouldn't have this problem any longer.
